"""Add Answer table, quiz_name unique, duration_minutes to Quiz

Revision ID: 8aef6329cd07
Revises: dc8cfc959488
Create Date: 2025-06-23 22:13:25.922449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aef6329cd07'
down_revision: Union[str, Sequence[str], None] = 'dc8cfc959488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_id')
    # ### end Alembic commands ###
